import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./_components/_provider/chakraProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Nistagram",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="h-full">
			<body className={inter.className}>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
