import { inter } from "./_utils/fonts";
import "./globals.css";

export const metadata = {
	title: "Nistagram",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="h-full">
			<body className={`${inter.className}`}>{children}</body>
		</html>
	);
}
